// 389. Find the Difference
// Easy

// 2683

// 381

// Add to List

// Share
// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"
 

// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.
// Accepted
// 383,076
// Submissions
// 632,878
// Seen this question in a real interview before?

// Yes

// No

var findTheDifference = function(s, t) {
    //Transforming the strings in arrays
    const sArr = s.split(""), tArr = t.split("")
   
    for (let i = 0; i < sArr.length; i++) {
        for (let j = 0; j < sArr.length; j++) {
            
       //If sArr and tArr have same element, this element will be deleted
           if (sArr[i] === tArr[j]) {
               tArr.splice(j, 1);
               break
           }
       }
     }
       
       //Return the element that wasn't deleted in the condition above
       return tArr.join("")
   };

let s = "abcd", t = "abcde";

console.log(findTheDifference(s, t))